// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251005110321_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TrasaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrasaId");

                    b.ToTable("Kursy");
                });

            modelBuilder.Entity("api.Models.KursyPrzystanek", b =>
                {
                    b.Property<int?>("KursId")
                        .HasColumnType("int");

                    b.Property<int?>("PrzystanekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Godzina")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("KursId", "PrzystanekId");

                    b.HasIndex("PrzystanekId");

                    b.ToTable("KursyPrzystanki");
                });

            modelBuilder.Entity("api.Models.Przystanek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Przystanki");
                });

            modelBuilder.Entity("api.Models.Trasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazwaLinii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trasy");
                });

            modelBuilder.Entity("api.Models.Kurs", b =>
                {
                    b.HasOne("api.Models.Trasa", "Trasa")
                        .WithMany("Kursy")
                        .HasForeignKey("TrasaId");

                    b.Navigation("Trasa");
                });

            modelBuilder.Entity("api.Models.KursyPrzystanek", b =>
                {
                    b.HasOne("api.Models.Kurs", "Kurs")
                        .WithMany("KursyPrzystanki")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Przystanek", "Przystanek")
                        .WithMany("KursyPrzystanki")
                        .HasForeignKey("PrzystanekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Przystanek");
                });

            modelBuilder.Entity("api.Models.Kurs", b =>
                {
                    b.Navigation("KursyPrzystanki");
                });

            modelBuilder.Entity("api.Models.Przystanek", b =>
                {
                    b.Navigation("KursyPrzystanki");
                });

            modelBuilder.Entity("api.Models.Trasa", b =>
                {
                    b.Navigation("Kursy");
                });
#pragma warning restore 612, 618
        }
    }
}
